version: '2.4'
services:

   cherrymusic:
    #build:
    #  context: .
    #  dockerfile: alpine.Dockerfile
    image: tobi312/rpi-cherrymusic:alpine
    container_name: cherrymusic
    restart: unless-stopped
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
    environment:
      CONFIG_DOWNLOAD_ENABLE: "1" # optional, for first start!
    #  KEY: "VAR"
    volumes:
      - ./config:/cherrymusic/.config/cherrymusic:rw
      - ./data:/cherrymusic/.local/share/cherrymusic:rw
      - ./Music:/cherrymusic/Music:ro
      - ./ssl:/cherrymusic/ssl:ro
    healthcheck:
      test: ["CMD-SHELL", "nc -nzv -w 3 127.0.0.1 8080 || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3
